### ISSUE TITLE
Pidgin loads all logged steam conversations as new messages at startup.

### ISSUE THREAD

**Issue by Toqozz** [EionRobb/pidgin-opensteamworks#105]
1. Start pidgin and wait to sign into steam.
2. All previous conversations load in as if they were new chats.

Quite an annoying bug, only since 1.6.

I am logging conversations via the default pidgin method, have tried disabling the "history" plugin to no avail.

**Comment by EionRobb** [comment]
Yeah, sorry about that.  :(

In my rush to get v1.6 out to fix the login, I didn't give enough TLC to the new offline history download feature.  Disabling the history plugin won't have an effect as it's part of the Steam plugin.

The intended feature is to only download messages that were sent by other people between the time you were last online and now, but for some reason the checks to make sure it's only newer than the last message aren't happening correctly.

**Comment by Toqozz** [comment]
Take your time :)

**Comment by EionRobb** [comment]
Latest commit might improve the situation a little, but needs more testing :)

**Comment by Toqozz** [comment]
Fixed for now, will report after more usage!

**Comment by EionRobb** [comment]
I'm worried I messed things up worse now :( I'm not receiving any messages from other people, only history. It's probably that I'm not accounting for server time offset or something

**Comment by Toqozz** [comment]
It's the same for me, if its worth anything, offline messages are the least important feature for me as I can log in through steamcommunity and have a look anyway.

Perhaps realizing what messages are unseen based on time is not the ideal way?  I don't know how you're doing it right now, but how about;

if lastloggedmsgID != newestmsgID: print msg

I'm no expert though.

**Comment by EionRobb** [comment]
Alrighty, I've released a 1.6.1 but no 64bit so's yet
It mostly fixes the history, but adds a setting to turn it off as needed

**Comment by Toqozz** [comment]
Heres a 64bit .so :)

http://filebin.net/gaw8s26wvn

**Comment by Shados** [comment]
Just had this happen to me on 1.6.1, sadly looks like it's not fixed yet. Did seem to take a lot longer before it happened this time, oddly.

**Comment by EionRobb** [comment]
@Shados was it just the first time you used v1.6.1 or was it after the first time?

**Comment by Toqozz** [comment]
Admittedly, I have not been using the history feature as pidgin seems to crash at unexpected times when it is enabled, whether it be at sign on or at some point after.

**Comment by EionRobb** [comment]
@Toqozz if you're getting crashes, can you please open a new issue with a backtrace so we can fix? :)

**Comment by Toqozz** [comment]
I’ve been away, but when I get back (wed) I will.

**Comment by Toqozz** [comment]
Traced issue to skype instead.

**Comment by EionRobb** [comment]
@toqozz please open an issue on the Skype plugin github issue tracker with a backtrace :)

**Comment by ChristophHaag** [comment]
Well, the actual issue is not solved yet. I still get the chat history as new messages when the plugin reconnects.

**Comment by EionRobb** [comment]
@ChristophHaag can you double check that you're using 1.6.1 (check in Help->Plugin Information) and that you're not still using 1.6?

**Comment by ChristophHaag** [comment]
Oops, I totally forgot updating the archlinux package. Was still using the google code svn repository. From a first look it looks like it is indeed solved. Sorry for the noise.

**Comment by EionRobb** [comment]
I like it noisy ;)

Thanks for following up :)
