### ISSUE TITLE
Login Fails and Captchas ad infinitum

### ISSUE THREAD

**Issue by verwirrungstaktiker** [EionRobb/pidgin-opensteamworks#134]
I freshly installed pidgin-opensteamworks (v1.6.1) and login fails. After the first fail, Captchas appear, but shortly after answering a new one appears.
The password is definitly the correct one. I even copied it from the account.xml to log into Steam and it worked.
SteamGuard is active and SteamGuard Code in pidgin is empty.

Here a log with two Captchas:

[purple-debug.txt](https://github.com/EionRobb/pidgin-opensteamworks/files/135448/purple-debug.txt)

I use Gentoo Linux with pidgin 2.10.12.

**Comment by EionRobb** [comment]
I've just committed a fix for the infinite captcha that might help with logins too, if you want to give it a whirl?

**Comment by verwirrungstaktiker** [comment]
I checked it out.

Yes, the infinite captcha stopped but I still cannot login. Error message is "incorrect login". When I click in the Pidgin error message on "Re-enable" the Steam account is enabled but doesn't try to go online.

(11:25:44) connection: Cannot connect to account MySteamUser without a password.

Furthermore, after the failed login, the password field in the account config was cleared.
Looking at the code, line 1263 in libsteam.c seems to be responsible for the last one.

And I made 100% sure both login and password were correct. I typed them into a text-editor and copied and pasted them to pidgin and steam.
